#!/bin/bash
# ============================================================================
# Akamai Cloud Wazuh Quick-Start - Credential Generation
# ============================================================================
# This script generates secure random passwords for Wazuh deployment:
#   - Admin dashboard password
#   - Kibanaserver internal password
#   - Agent registration password
#
# Passwords are stored in:
#   - .credentials file (plaintext, chmod 600)
#   - Kubernetes secrets (base64 encoded)
#   - internal_users.yml (bcrypt hashed)
#
# Usage: ./generate-credentials.sh <output-dir>
# ============================================================================

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Logging functions
log_info() { echo -e "${BLUE}ℹ${NC} $1"; }
log_success() { echo -e "${GREEN}✓${NC} $1"; }
log_warning() { echo -e "${YELLOW}⚠${NC} $1"; }
log_error() { echo -e "${RED}✗${NC} $1"; }

# Check arguments
if [[ $# -lt 1 ]]; then
    log_error "Usage: $0 <output-directory>"
    exit 1
fi

OUTPUT_DIR="$1"
CREDENTIALS_FILE="${OUTPUT_DIR}/.credentials"
INTERNAL_USERS_FILE="${OUTPUT_DIR}/internal_users.yml"

# Create output directory if it doesn't exist
mkdir -p "$OUTPUT_DIR"

# ============================================================================
# Check for existing credentials
# ============================================================================
if [[ -f "$CREDENTIALS_FILE" ]]; then
    log_warning "Credentials file already exists: $CREDENTIALS_FILE"
    read -p "Do you want to regenerate credentials? (yes/no): " -r
    echo
    if [[ ! $REPLY =~ ^[Yy]es$ ]]; then
        log_info "Using existing credentials"
        exit 0
    fi
    log_warning "Regenerating credentials..."
fi

# ============================================================================
# Generate Random Passwords
# ============================================================================
log_info "Generating secure random passwords..."

# Generate 32-character random passwords
ADMIN_PASSWORD=$(openssl rand -base64 32 | tr -d "=+/" | cut -c1-32)
KIBANASERVER_PASSWORD=$(openssl rand -base64 32 | tr -d "=+/" | cut -c1-32)
WAZUH_API_PASSWORD=$(openssl rand -base64 32 | tr -d "=+/" | cut -c1-32)
AGENT_PASSWORD=$(openssl rand -base64 32 | tr -d "=+/" | cut -c1-32)
# Wazuh cluster key must be exactly 32 characters (hex keeps it 32 chars exactly)
WAZUH_CLUSTER_KEY=$(openssl rand -hex 16)

log_success "Random passwords generated"

# ============================================================================
# Generate Bcrypt Hashes
# ============================================================================
log_info "Generating bcrypt password hashes (this may take a minute)..."

# Function to generate bcrypt hash using docker
generate_bcrypt_hash() {
    local password="$1"
    # Use htpasswd via docker to generate bcrypt hash
    docker run --rm httpd:2.4-alpine htpasswd -bnBC 10 "" "$password" | tr -d ':\n' | sed 's/^[^$]*//'
}

# Check if docker is available
if ! command -v docker &> /dev/null; then
    log_error "Docker is required to generate bcrypt hashes but is not installed"
    log_error "Please install Docker: https://docs.docker.com/get-docker/"
    exit 1
fi

# Check if docker daemon is running
if ! docker ps &> /dev/null; then
    log_error "Docker daemon is not running. Please start Docker and try again."
    exit 1
fi

# Generate hashes
ADMIN_HASH=$(generate_bcrypt_hash "$ADMIN_PASSWORD")
KIBANASERVER_HASH=$(generate_bcrypt_hash "$KIBANASERVER_PASSWORD")

log_success "Bcrypt hashes generated"

# ============================================================================
# Create internal_users.yml
# ============================================================================
log_info "Creating internal_users.yml..."

cat > "$INTERNAL_USERS_FILE" <<EOF
# Wazuh Internal Users Configuration
# Generated by Akamai Cloud Wazuh Quick-Start
# Generated: $(date -u +"%Y-%m-%d %H:%M:%S UTC")

---
# Admin user - Full access to Wazuh Dashboard
admin:
  hash: "${ADMIN_HASH}"
  reserved: true
  backend_roles:
  - "admin"
  description: "Administrator user with full access"

# Kibanaserver - Internal service account
kibanaserver:
  hash: "${KIBANASERVER_HASH}"
  reserved: true
  description: "Internal user for Wazuh Dashboard to Indexer communication"

# Additional predefined users (disabled by default)
# Uncomment and set passwords if needed

#kibanaro:
#  hash: ""
#  reserved: false
#  backend_roles:
#  - "kibanauser"
#  - "readall"
#  attributes:
#    attribute1: "value1"
#  description: "Read-only user for dashboards"

#logstash:
#  hash: ""
#  reserved: false
#  backend_roles:
#  - "logstash"
#  description: "Logstash service account"

#readall:
#  hash: ""
#  reserved: false
#  backend_roles:
#  - "readall"
#  description: "Read-only user"

#snapshotrestore:
#  hash: ""
#  reserved: false
#  backend_roles:
#  - "snapshotrestore"
#  description: "Snapshot and restore user"
EOF

log_success "internal_users.yml created: $INTERNAL_USERS_FILE"

# ============================================================================
# Create Kustomize secret patches (wire the generated values into the deployment)
# ============================================================================
# The base wazuh-kubernetes manifests ship default plaintext credentials. These
# strategic-merge patches override the `data` of each Secret with the generated
# values so the running deployment uses strong, unique credentials. They are
# referenced from kubernetes/kustomization.yml under `patches:` and consumed by
# `kubectl apply -k`. The plaintext admin/kibanaserver passwords here match the
# bcrypt hashes written to internal_users.yml above.
log_info "Writing Kustomize secret patches..."

# base64-encode without a trailing newline (portable across GNU/BSD)
b64() { printf '%s' "$1" | base64 | tr -d '\n'; }

write_secret_patch() {
    # $1 = filename, $2 = secret name, then key=value pairs
    local file="$OUTPUT_DIR/$1"; local name="$2"; shift 2
    {
        echo "# Generated by generate-credentials.sh — do not commit."
        echo "apiVersion: v1"
        echo "kind: Secret"
        echo "metadata:"
        echo "  name: $name"
        echo "data:"
        while [[ $# -gt 0 ]]; do
            echo "  ${1%%=*}: $(b64 "${1#*=}")"
            shift
        done
    } > "$file"
    chmod 600 "$file"
}

# Dashboard admin login + filebeat→indexer auth (must match internal_users admin hash)
write_secret_patch "indexer-cred.patch.yaml"      "indexer-cred"      "username=admin"        "password=${ADMIN_PASSWORD}"
# Dashboard→indexer service account (must match internal_users kibanaserver hash)
write_secret_patch "dashboard-cred.patch.yaml"    "dashboard-cred"    "username=kibanaserver" "password=${KIBANASERVER_PASSWORD}"
# Wazuh API user (consumed by both manager and dashboard)
write_secret_patch "wazuh-api-cred.patch.yaml"    "wazuh-api-cred"    "username=wazuh-wui"    "password=${WAZUH_API_PASSWORD}"
# Agent registration password
write_secret_patch "wazuh-authd-pass.patch.yaml"  "wazuh-authd-pass"  "authd.pass=${AGENT_PASSWORD}"
# Manager cluster key (shared master/worker secret; default is publicly known)
write_secret_patch "wazuh-cluster-key.patch.yaml" "wazuh-cluster-key" "key=${WAZUH_CLUSTER_KEY}"

log_success "Secret patches written to: $OUTPUT_DIR"

# ============================================================================
# Save Credentials to File
# ============================================================================
log_info "Saving credentials to file..."

cat > "$CREDENTIALS_FILE" <<EOF
# ============================================================================
# Wazuh Deployment Credentials
# ============================================================================
# Generated: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
#
# IMPORTANT: Keep this file secure!
# - File permissions: $(stat -c %a "$CREDENTIALS_FILE" 2>/dev/null || stat -f %A "$CREDENTIALS_FILE" 2>/dev/null)
# - Do not commit to version control
# - Store securely (password manager, secrets vault)
# ============================================================================

# ----------------------------------------------------------------------------
# Wazuh Dashboard Access
# ----------------------------------------------------------------------------
# URL: https://wazuh.${DOMAIN:-YOUR_DOMAIN}
# Username: admin
WAZUH_DASHBOARD_PASSWORD="${ADMIN_PASSWORD}"

# ----------------------------------------------------------------------------
# Wazuh API Access (Manager)
# ----------------------------------------------------------------------------
# Used for API calls to Wazuh Manager
# Default user: wazuh
WAZUH_API_PASSWORD="${WAZUH_API_PASSWORD}"

# ----------------------------------------------------------------------------
# Agent Registration Password
# ----------------------------------------------------------------------------
# Used by agents to register with the manager
# Required for agent deployment
WAZUH_AGENT_PASSWORD="${AGENT_PASSWORD}"

# ----------------------------------------------------------------------------
# Internal Service Passwords (Do not modify)
# ----------------------------------------------------------------------------
# Kibanaserver - Dashboard to Indexer communication
KIBANASERVER_PASSWORD="${KIBANASERVER_PASSWORD}"

# Manager cluster key (shared master/worker secret)
WAZUH_CLUSTER_KEY="${WAZUH_CLUSTER_KEY}"

# ----------------------------------------------------------------------------
# Kubernetes Secret Values (for reference)
# ----------------------------------------------------------------------------
# These values are automatically deployed as Kubernetes secrets
# Base64 encoded values:
#
# ADMIN_PASSWORD_BASE64=$(echo -n "$ADMIN_PASSWORD" | base64)
# KIBANASERVER_PASSWORD_BASE64=$(echo -n "$KIBANASERVER_PASSWORD" | base64)
# AGENT_PASSWORD_BASE64=$(echo -n "$AGENT_PASSWORD" | base64)

# ----------------------------------------------------------------------------
# Quick Reference Commands
# ----------------------------------------------------------------------------
# View credentials:
#   cat $(realpath "$CREDENTIALS_FILE")
#
# Get admin password:
#   grep WAZUH_DASHBOARD_PASSWORD $(realpath "$CREDENTIALS_FILE") | cut -d'=' -f2 | tr -d '"'
#
# Get agent password:
#   grep WAZUH_AGENT_PASSWORD $(realpath "$CREDENTIALS_FILE") | cut -d'=' -f2 | tr -d '"'
#
# Rotate passwords:
#   rm $(realpath "$CREDENTIALS_FILE") && ./kubernetes/scripts/generate-credentials.sh
#
# ============================================================================
EOF

# Set secure permissions
chmod 600 "$CREDENTIALS_FILE"

log_success "Credentials saved to: $CREDENTIALS_FILE"
log_warning "File permissions set to 600 (read/write for owner only)"

# ============================================================================
# Display Summary
# ============================================================================
echo ""
log_success "Credential generation completed successfully!"
echo ""
log_info "Generated files:"
echo "  • Credentials file: $CREDENTIALS_FILE (chmod 600)"
echo "  • Internal users:   $INTERNAL_USERS_FILE"
echo ""
log_info "Generated passwords:"
echo "  • Admin dashboard: ******* (32 chars)"
echo "  • Kibanaserver:    ******* (32 chars)"
echo "  • Agent password:  ******* (32 chars)"
echo ""
log_warning "Security reminders:"
echo "  • Store credentials securely (password manager recommended)"
echo "  • Do not commit .credentials file to version control"
echo "  • Change admin password after first login"
echo "  • Rotate passwords regularly (every 90 days recommended)"
echo ""
log_info "To view credentials:"
echo "  cat $CREDENTIALS_FILE"
echo ""
